name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run trailing white space check with git
      run: |
        git diff --check `git rev-list HEAD | tail -n 1`..
    - name: Run PlatformIO build tests
      run: |
        platformio run -e esp32-edge
#    - name: Run PlatformIO unit-tests
#      run: |
#        platformio test -e unit_test
    - name: Run PlatformIO code checks
      run: |
        platformio check -e esp32-edge --skip-packages --fail-on-defect high
